// <auto-generated />
using System;
using MeroShareBot.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeroShareBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260716163011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MeroShareBot.Shared.Data.Entities.ChatSettingsEntity", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("DefaultAccountId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("NotifyEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ChatId");

                    b.ToTable("ChatSettings");
                });

            modelBuilder.Entity("MeroShareBot.Shared.Data.Entities.LinkedAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AppliedShareIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("AutoApplyEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("AutoApplyKitta")
                        .HasColumnType("int");

                    b.Property<string>("AutoApplyPromptedShareIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Dp")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EncryptedCrn")
                        .HasColumnType("longtext");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EncryptedPin")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("Username", "Dp")
                        .IsUnique();

                    b.ToTable("LinkedAccounts");
                });

            modelBuilder.Entity("MeroShareBot.Shared.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ChatId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MeroShareBot.Shared.Data.Entities.WatchlistEntity", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ChatId", "Symbol");

                    b.ToTable("WatchlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
